---
- name: Configure Distribution Switches (Layer 3)
  hosts: cdswitches
  gather_facts: no

  tasks:
    - name: Enable Global Routing
      cisco.ios.ios_config:
        lines: ip routing

    - name: Create VLANs
      cisco.ios.ios_vlans:
        config:
          - name: "{{ item.name }}"
            vlan_id: "{{ item.id }}"
      loop: "{{ campus_vlans }}"

    - name: Configure L3 Uplinks to Routers
      cisco.ios.ios_config:
        lines:
          - no switchport
          - description "{{ item.desc }}"
          - ip address {{ item.ip }} 255.255.255.252
          - no shutdown
        parents: "interface {{ item.int }}"
      loop:
        - { int: "Ethernet0/1", desc: "TO_R1_L1", ip: "{{ r1_l1_ip }}" }
        - { int: "Ethernet0/2", desc: "TO_R1_L2", ip: "{{ r1_l2_ip }}" }
        - { int: "Ethernet1/1", desc: "TO_R2_L1", ip: "{{ r2_l1_ip }}" }
        - { int: "Ethernet1/2", desc: "TO_R2_L2", ip: "{{ r2_l2_ip }}" }

    - name: Configure Cloud Bridge Port for Servers
      cisco.ios.ios_config:
        lines:
          - description "LINK_TO_WINDOWS_SERVER_VIA_CLOUD"
          - switchport mode access
          - switchport access vlan 100
          - no shutdown
        parents: interface Ethernet3/3

    - name: Configure SVIs and HSRP
      cisco.ios.ios_config:
        lines:
          - ip address {{ item.cd1_ip if inventory_hostname == 'cd1' else item.cd2_ip }} 255.255.255.0
          - standby {{ item.id }} ip {{ item.vip }}
          - standby {{ item.id }} priority {{ hsrp_priority }}
          - standby {{ item.id }} preempt
        parents: "interface Vlan{{ item.id }}"
      loop: "{{ campus_vlans }}"

    - name: Configure OSPF
      cisco.ios.ios_config:
        lines:
          - router ospf {{ ospf_process_id }}
          - router-id {{ router_id }}
          - network 172.16.0.0 0.0.255.255 area 0
          # This advertises all the user VLANs to the routers:
          - passive-interface default
          - no passive-interface Ethernet0/1
          - no passive-interface Ethernet0/2
          - no passive-interface Ethernet1/1
          - no passive-interface Ethernet1/2

    - name: Save Configuration
      cisco.ios.ios_command:
        commands: write memory
