---
- name: Provision Library Access Layer (Bottom-Up)
  hosts: accswitches
  gather_facts: no

  tasks:
    - name: Configure Global STP and VTP
      cisco.ios.ios_config:
        lines:
          - spanning-tree mode {{ global_stp_settings.mode }}
          - spanning-tree portfast bpduguard default
          - vtp mode transparent
          - spanning-tree extend system-id

    - name: Create VLANs
      cisco.ios.ios_vlans:
        config:
          - name: "{{ item.name }}"
            vlan_id: "{{ item.id }}"
      loop: "{{ campus_vlans }}"

    - name: Configure Uplink Trunks to CD Switches
      cisco.ios.ios_config:
        lines:
          - description {{ item.description }}
          - switchport trunk encapsulation dot1q
          - switchport mode {{ item.mode }}
          - switchport trunk allowed vlan all
          - no shutdown
        parents: "interface {{ item.name }}"
      loop: "{{ uplink_config }}"

    - name: Configure Access Ports from Host Vars
      cisco.ios.ios_config:
        lines:
          - description "{{ item.desc }}"
          - switchport mode access
          - switchport access vlan {{ item.vlan }}
          - spanning-tree portfast
          - spanning-tree bpduguard enable
        parents: "interface {{ item.port }}"
      loop: "{{ access_ports }}"
      when: access_ports is defined

    - name: Save Configuration to NVRAM
      cisco.ios.ios_config:
        save_when: always
...
